roslaunch interbotix_xsturret_simple_interface xsturret_simple_interface.launch robot_model:=vxxms
echo extra detail here: https://github.com/Interbotix/interbotix_ros_turrets/tree/236b8de875ebea6f7e3b1054dbe16a9794016d69/interbotix_ros_xsturrets/examples/interbotix_xsturret_simple_interface
