roslaunch interbotix_xsturret_gazebo xsturret_gazebo.launch robot_model:=pxxls
echo more detail here: https://github.com/Interbotix/interbotix_ros_turrets/tree/236b8de875ebea6f7e3b1054dbe16a9794016d69/interbotix_ros_xsturrets/interbotix_xsturret_gazebo
